language: node_js
node_js:
  - "14.10"
branches:
  only:
    - master
script:
  - npm run export
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.chrisyarie.com
  region: us-east-1
  skip_cleanup: true
  acl: public_read
  local_dir: public
  detect_encoding: true
  on:
    branch: master